name: CI

on:
  push:
    branches: [master]
  pull_request:
    paths:
      - "**.js"
      - "package.json"
      - ".github/workflows/ci.yml"

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: ["18", "20", "22"]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: pnpm install
      - run: pnpm test
      - run: pnpm run report -- --colors
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage/coverage-final.json
